### ISSUE TITLE
Example Scene

### ISSUE THREAD

**Issue by nocktua** [Hobbes02/GodotPlatformerPathfinding#1]
This project seems good, but due to not having an example scene on how to implement it, makes it confusing to use aside from setting up the Resource and initializing the Pathfinder. 

The only scene present in the project is a tscn with some broken dependencies, so it doesn't help either.

**Comment by Hobbes02** [comment]
Thanks for the feedback!
I've just started work on a simple demo scene, should be out Nov. 25th UTC

**Comment by Hobbes02** [comment]
I've just added a demo, fixed the dependencies, and simplified the way pathfinding agents work. I hope this solves any problems you were having. Please let me know if you have any more questions.

**Comment by nocktua** [comment]
Thank you for your hard work! Might consider contributing for a C# version of the addon.

**Comment by Hobbes02** [comment]
I don't have any experience with C#, but if you wanted to make a wrapper (or even a full port), you should go for it.
